name: Ultroid workflow

on:
  push:
    branches:
      - main  # Adjust this branch name if needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev
          sudo apt-get install -y pkg-config

      - name: Update dependencies
        run: pip install --upgrade cython setuptools

      - name: Upgrade Pip
        run: pip install --upgrade pip

      - name: Cloning Private repo
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_NAME }}/${{ secrets.PR }} PR

      - name: Running bomt
        timeout-minutes: 350
        continue-on-error: true
        run: |
          sudo bash ultroid.sh

      - name: Loop
        continue-on-error: true
        run: |
          git clone https://github.com/${{ secrets.GH_NAME }}/TG-UB-workflow loop
          cd loop || exit 1
          echo $(TZ='${{ secrets.TZ }}' date) >> loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop $(TZ='${{ secrets.TZ }}' date)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_NAME }}/TG-UB-workflow HEAD:main
